-- Rex Custom Defines
-- Diplomacy Defines

NDefines.NDiplomacy.MIN_ASKED_TRADE_POWER = 0
NDefines.NDiplomacy.MAX_ASKED_TRADE_POWER = 0

NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = -0
NDefines.NDiplomacy.REVANCHISM_MONTHLY_DECAY = 0.335

NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 12
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200

NDefines.NDiplomacy.REMOVE_FREECITY_INFLUENCE_COST = 0
NDefines.NDiplomacy.IMPERIAL_REFORM_COST = 75
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.25
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 30
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.01

-- Country Defines

NDefines.NCountry.PROSPERITY_INCREASE_SIZE = 1
NDefines.NCountry.PROSPERITY_MONTHLY_DECLINE = -1

NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.MONARCH_MAX_SKILL = 6
NDefines.NCountry.ELECTIVE_LOCAL_MONARCH_MIN_BONUS = 1
NDefines.NCountry.ELECTIVE_FOREIGN_MONARCH_MIN_BONUS = 1

NDefines.NCountry.ESTATE_PROVINCE_HAPPINESS_DECREASE = 1.5

NDefines.NCountry.HRE_MAX_RANK = 2

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4

NDefines.NCountry.NAT_FOCUS_YEARS = 15

NDefines.NCountry.PS_MOVE_CAPITAL = 100
NDefines.NCountry.PS_MOVE_CAPITAL_EXTRA = 25
NDefines.NCountry.PS_MOVE_TRADE_PORT = 100
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 70
NDefines.NCountry.PS_BOOST_MILITARIZATION = 30

NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = -0
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = -0
NDefines.NCountry.BREAK_ALLIANCE_PRESTIGE_LOSS = 0

NDefines.NCountry.CORE_LOSE_PRESTIGE = -0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = -0

NDefines.NCountry.MONTHS_TO_CORE_MAXIMUM = 24
NDefines.NCountry.MONTHS_TO_CORE = 12
NDefines.NCountry.MONTHS_TO_CORE_MINIMUM = 12
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 6

NDefines.NCountry.REVOLT_SIZE_DEVELOPMENT_MULTIPLIER = 0.1
NDefines.NCountry.REVOLT_SIZE_BASE = 1

-- Economy Defines

NDefines.NEconomy.DEBASE_MONTHS_PER_CHARGE = 36

NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 25

NDefines.NEconomy.INFLATION_FROM_LOAN = 0.15
NDefines.NEconomy.INFLATION_FROM_PEACE_GOLD = 0.01

NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.03

NDefines.NEconomy.EDICTS_COST_INCREASE = 1.0
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 60

NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.08
NDefines.NEconomy.LIGHT_SHIP_MAINT_FACTOR = 0.07
NDefines.NEconomy.GALLEY_MAINT_FACTOR = 0.06
NDefines.NEconomy.TRANSPORT_MAINT_FACTOR = 0.06

